services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - html:/app/frontend/dist
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - html:/usr/dist
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend
  mongo:
    image: mongo
    restart: always
    ports:
      - 3456:27017
    volumes:
      - ./backend/src/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: visit-this-please
volumes:
  html:
  mongo_data:
